#!/usr/bin/env bash
# shellcheck shell=bash
#
# harbor-deploy — Write a new root image to the inactive A/B partition and reboot
#
# Called via sudo by the GitHub Actions runner. Image must be pre-staged at
# IMAGE (below) before invoking. Not intended for direct use — use deploy.sh
# for manual deploys.
#
set -euo pipefail

IMAGE="/tmp/harbor_srv-root.img.zst"

MOUNT_DIR=""

cleanup() {
    if [ -n "$MOUNT_DIR" ] && mountpoint -q "$MOUNT_DIR" 2>/dev/null; then
        umount -R "$MOUNT_DIR" 2>/dev/null || true
    fi
    [ -n "$MOUNT_DIR" ] && rmdir "$MOUNT_DIR" 2>/dev/null || true
}
trap cleanup EXIT

if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: must run as root" >&2
    exit 1
fi

if [ ! -f "$IMAGE" ]; then
    echo "ERROR: ${IMAGE} not found — stage the artifact there before calling harbor-deploy" >&2
    exit 1
fi

CONF="/etc/harbor/partitions.conf"
if [ ! -f "$CONF" ]; then
    echo "ERROR: ${CONF} not found. Was this system installed with install.sh?" >&2
    exit 1
fi

# shellcheck source=/dev/null
source "$CONF"

ACTIVE_ROOT=$(findmnt -n -o SOURCE /)
echo ":: Active root: ${ACTIVE_ROOT}"

if [ "$ACTIVE_ROOT" = "$ROOT_A_DEV" ]; then
    TARGET_DEV="$ROOT_B_DEV"
    TARGET_ENTRY_BASE="harbor-b"
    TARGET_LABEL="Root B"
    TARGET_PARTUUID="$ROOT_B_PARTUUID"
elif [ "$ACTIVE_ROOT" = "$ROOT_B_DEV" ]; then
    TARGET_DEV="$ROOT_A_DEV"
    TARGET_ENTRY_BASE="harbor-a"
    TARGET_LABEL="Root A"
    TARGET_PARTUUID="$ROOT_A_PARTUUID"
else
    echo "ERROR: Active root ${ACTIVE_ROOT} doesn't match Root A (${ROOT_A_DEV}) or Root B (${ROOT_B_DEV})" >&2
    exit 1
fi

BOOT_TRIES=3
TARGET_ENTRY="${TARGET_ENTRY_BASE}+${BOOT_TRIES}.conf"

echo ":: Target: ${TARGET_LABEL} (${TARGET_DEV})"

echo ":: Decompressing and writing image..."
zstd -d "$IMAGE" --stdout | dd of="$TARGET_DEV" bs=4M conv=fsync status=progress
sync

echo ":: Resizing filesystem..."
e2fsck -f -y "$TARGET_DEV" || true
resize2fs "$TARGET_DEV"

MOUNT_DIR="/tmp/harbor-deploy-$$"
mkdir -p "$MOUNT_DIR"
mount "$TARGET_DEV" "$MOUNT_DIR"

cat > "${MOUNT_DIR}/etc/fstab" << EOF
# harbor_srv fstab — generated by harbor-deploy
PARTUUID=${TARGET_PARTUUID}    /          ext4  rw,relatime          0 1
PARTUUID=${ESP_PARTUUID}       /boot/efi  vfat  rw,relatime,fmask=0077,dmask=0077  0 2
PARTUUID=${DATA_PARTUUID}      /data      ext4  rw,relatime          0 2
EOF

mkdir -p "${MOUNT_DIR}/etc/harbor"
cp "$CONF" "${MOUNT_DIR}/etc/harbor/partitions.conf"

# --- Inject Kerberos secrets (if provided) ---
if [ -n "${KRB5_SECRETS_B64:-}" ]; then
    echo ":: Injecting Kerberos secrets..."
    mkdir -p "${MOUNT_DIR}/var/lib/krb5kdc"
    # Extract only the two expected paths (KDC database directory and server keytab).
    # Explicit path arguments prevent a malformed or compromised tarball from
    # writing files to arbitrary locations under $MOUNT_DIR.
    printf '%s' "$KRB5_SECRETS_B64" | base64 -d | tar -xz -C "$MOUNT_DIR" \
        --no-same-owner --owner=0 --group=0 \
        var/lib/krb5kdc/ etc/krb5.keytab
    chmod 700 "${MOUNT_DIR}/var/lib/krb5kdc"
    # Use find instead of a glob to avoid following symlinks — a crafted tarball
    # could include a symlink whose target would otherwise be chmod'd on the
    # running system.
    find "${MOUNT_DIR}/var/lib/krb5kdc" -maxdepth 1 ! -type l -exec chmod 600 {} +
    chmod 600 "${MOUNT_DIR}/etc/krb5.keytab"
    # Clear the secret from the environment — it has been consumed; child
    # processes forked later in this script should not inherit it.
    unset KRB5_SECRETS_B64
    echo ":: Kerberos secrets injected."
else
    echo "WARNING: KRB5_SECRETS_B64 not set — Kerberos will not be functional" >&2
fi

ESP_MOUNT=$(findmnt -n -o TARGET /boot/efi 2>/dev/null || echo "")
if [ -z "$ESP_MOUNT" ]; then
    mkdir -p /boot/efi
    mount "PARTUUID=${ESP_PARTUUID}" /boot/efi
    ESP_MOUNT="/boot/efi"
fi
cp "${MOUNT_DIR}/boot/vmlinuz-linux" "${ESP_MOUNT}/"
cp "${MOUNT_DIR}/boot/intel-ucode.img" "${ESP_MOUNT}/"
cp "${MOUNT_DIR}/boot/initramfs-linux.img" "${ESP_MOUNT}/"

ENTRIES_DIR="${ESP_MOUNT}/loader/entries"
rm -f "${ENTRIES_DIR}/${TARGET_ENTRY_BASE}.conf"
rm -f "${ENTRIES_DIR}/${TARGET_ENTRY_BASE}"+*.conf
cat > "${ENTRIES_DIR}/${TARGET_ENTRY}" << EOF
title   Harbor Srv (${TARGET_LABEL})
linux   /vmlinuz-linux
initrd  /intel-ucode.img
initrd  /initramfs-linux.img
options root=PARTUUID=${TARGET_PARTUUID} rw ipv6.disable=1 panic=10
EOF

sed -i "s|^default .*|default ${TARGET_ENTRY_BASE}*|" "${ESP_MOUNT}/loader/loader.conf"

echo ":: Boot default set to: ${TARGET_ENTRY} (${BOOT_TRIES} tries before fallback)"

umount "$MOUNT_DIR"
rmdir "$MOUNT_DIR"

echo ""
echo "=== Deploy complete — rebooting in 60s ==="
echo "New root written to ${TARGET_LABEL} (${TARGET_DEV})"
# Schedule reboot via a detached systemd timer so this script can exit 0 cleanly
# before the machine goes down. The runner records the step as succeeded; the
# verify job in the workflow then polls for the offline→online transition.
# --no-block: return immediately after creating the timer unit (do not wait for it to fire).
# --on-active=60: 60s gives the runner enough time to finish job cleanup and report
# success to GitHub before the machine goes down.
systemd-run --no-block --on-active=60 /usr/bin/systemctl reboot
