#!/usr/bin/env bash
#
# deploy.sh — Deploy a new root image to the inactive A/B partition
#
# Detects the active root, writes the image to the other partition,
# updates systemd-boot to boot the new root, and reboots.
#
# Usage: sudo ./scripts/deploy.sh <root-image.img.zst>
#
set -euo pipefail

MOUNT_DIR=""

cleanup() {
    if [ -n "$MOUNT_DIR" ] && mountpoint -q "$MOUNT_DIR" 2>/dev/null; then
        umount -R "$MOUNT_DIR" 2>/dev/null || true
    fi
    [ -n "$MOUNT_DIR" ] && rmdir "$MOUNT_DIR" 2>/dev/null || true
}
trap cleanup EXIT

IMAGE="${1:-}"

if [ -z "$IMAGE" ]; then
    echo "Usage: $0 <root-image.img.zst>"
    exit 1
fi

if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: must run as root" >&2
    exit 1
fi

if [ ! -f "$IMAGE" ]; then
    echo "ERROR: ${IMAGE} not found" >&2
    exit 1
fi

CONF="/etc/harbor/partitions.conf"
if [ ! -f "$CONF" ]; then
    echo "ERROR: ${CONF} not found. Was this system installed with install.sh?" >&2
    exit 1
fi

# shellcheck source=/dev/null
source "$CONF"

# Determine active root
ACTIVE_ROOT=$(findmnt -n -o SOURCE /)
echo ":: Active root: ${ACTIVE_ROOT}"

if [ "$ACTIVE_ROOT" = "$ROOT_A_DEV" ]; then
    TARGET_DEV="$ROOT_B_DEV"
    TARGET_ENTRY_BASE="harbor-b"
    TARGET_LABEL="Root B"
    TARGET_PARTUUID="$ROOT_B_PARTUUID"
elif [ "$ACTIVE_ROOT" = "$ROOT_B_DEV" ]; then
    TARGET_DEV="$ROOT_A_DEV"
    TARGET_ENTRY_BASE="harbor-a"
    TARGET_LABEL="Root A"
    TARGET_PARTUUID="$ROOT_A_PARTUUID"
else
    echo "ERROR: Active root ${ACTIVE_ROOT} doesn't match Root A (${ROOT_A_DEV}) or Root B (${ROOT_B_DEV})" >&2
    exit 1
fi

BOOT_TRIES=3
TARGET_ENTRY="${TARGET_ENTRY_BASE}+${BOOT_TRIES}.conf"

echo ":: Target: ${TARGET_LABEL} (${TARGET_DEV})"

# Write image to inactive partition
echo ":: Decompressing and writing image..."
zstd -d "$IMAGE" --stdout | dd of="$TARGET_DEV" bs=4M conv=fsync status=progress
sync

# Resize filesystem to fill partition
echo ":: Resizing filesystem..."
e2fsck -f -y "$TARGET_DEV" || true
resize2fs "$TARGET_DEV"

# Mount target to update fstab and copy kernel
MOUNT_DIR="/tmp/harbor-deploy-$$"
mkdir -p "$MOUNT_DIR"
mount "$TARGET_DEV" "$MOUNT_DIR"

# Write fstab — always regenerate from known partition metadata
cat > "${MOUNT_DIR}/etc/fstab" << EOF
# harbor_srv fstab — generated by deploy.sh
PARTUUID=${TARGET_PARTUUID}    /          ext4  rw,relatime          0 1
PARTUUID=${ESP_PARTUUID}       /boot/efi  vfat  rw,relatime,fmask=0077,dmask=0077  0 2
PARTUUID=${DATA_PARTUUID}      /data      ext4  rw,relatime          0 2
EOF

# Copy partition config to new root
mkdir -p "${MOUNT_DIR}/etc/harbor"
cp "$CONF" "${MOUNT_DIR}/etc/harbor/partitions.conf"

# Copy kernel and initramfs to ESP
ESP_MOUNT=$(findmnt -n -o TARGET /boot/efi 2>/dev/null || echo "")
if [ -z "$ESP_MOUNT" ]; then
    mkdir -p /boot/efi
    mount "PARTUUID=${ESP_PARTUUID}" /boot/efi
    ESP_MOUNT="/boot/efi"
fi
cp "${MOUNT_DIR}/boot/vmlinuz-linux" "${ESP_MOUNT}/"
cp "${MOUNT_DIR}/boot/initramfs-linux.img" "${ESP_MOUNT}/"

# Write boot entry with try-counter for automatic fallback.
# systemd-boot decrements the counter on each boot attempt.
# systemd-bless-boot.service renames it to the blessed form on success.
# If all tries are exhausted, systemd-boot skips this entry and falls back.
ENTRIES_DIR="${ESP_MOUNT}/loader/entries"
rm -f "${ENTRIES_DIR}/${TARGET_ENTRY_BASE}.conf"
rm -f "${ENTRIES_DIR}/${TARGET_ENTRY_BASE}"+*.conf
cat > "${ENTRIES_DIR}/${TARGET_ENTRY}" << EOF
title   Harbor Srv (${TARGET_LABEL})
linux   /vmlinuz-linux
initrd  /initramfs-linux.img
options root=PARTUUID=${TARGET_PARTUUID} rw
EOF

# Set default using a glob so it matches both the counted and blessed forms.
# e.g. "harbor-b*" matches "harbor-b+3.conf", "harbor-b+2-1.conf", "harbor-b.conf"
sed -i "s|^default .*|default ${TARGET_ENTRY_BASE}*|" "${ESP_MOUNT}/loader/loader.conf"

echo ":: Boot default set to: ${TARGET_ENTRY} (${BOOT_TRIES} tries before fallback)"

umount "$MOUNT_DIR"
rmdir "$MOUNT_DIR"

echo ""
echo "=== Deploy complete ==="
echo "New root written to ${TARGET_LABEL} (${TARGET_DEV})"
echo "Rebooting in 5 seconds... (Ctrl+C to cancel)"
sleep 5
reboot
