#!/usr/bin/env bash
#
# install.sh — One-time installer for harbor_srv on NVMe
#
# Partitions the target disk with A/B root layout, writes the root image
# to partition A, and installs systemd-boot to the ESP.
#
# Run from the live ISO or any rescue environment:
#   sudo ./scripts/install.sh /dev/nvme0n1 output/harbor_srv-root.img.zst
#
set -euo pipefail

DISK="${1:-}"
IMAGE="${2:-}"

if [ -z "$DISK" ] || [ -z "$IMAGE" ]; then
    echo "Usage: $0 <disk> <root-image.img.zst>"
    echo "Example: $0 /dev/nvme0n1 harbor_srv-root.img.zst"
    exit 1
fi

if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: must run as root" >&2
    exit 1
fi

if [ ! -b "$DISK" ]; then
    echo "ERROR: ${DISK} is not a block device" >&2
    exit 1
fi

if [ ! -f "$IMAGE" ]; then
    echo "ERROR: ${IMAGE} not found" >&2
    exit 1
fi

# Derive partition paths (handles nvme0n1p1 vs sda1 naming)
if [[ "$DISK" == *nvme* ]] || [[ "$DISK" == *mmcblk* ]]; then
    PART_PREFIX="${DISK}p"
else
    PART_PREFIX="${DISK}"
fi

ESP="${PART_PREFIX}1"
ROOT_A="${PART_PREFIX}2"
ROOT_B="${PART_PREFIX}3"
DATA="${PART_PREFIX}4"

echo "=== harbor_srv Installer ==="
echo "Target disk: ${DISK}"
echo "Image:       ${IMAGE}"
echo ""
echo "Partition layout:"
echo "  ${ESP}   — 512M  ESP (FAT32)"
echo "  ${ROOT_A} — 10G   Root A (ext4)"
echo "  ${ROOT_B} — 10G   Root B (ext4)"
echo "  ${DATA}   — rest  Data (ext4)"
echo ""
echo "WARNING: This will DESTROY all data on ${DISK}!"
read -rp "Type YES to continue: " confirm
if [ "$confirm" != "YES" ]; then
    echo "Aborted."
    exit 1
fi

# --- Partition ---
echo ":: Partitioning ${DISK}..."
sgdisk --zap-all "$DISK"
sgdisk \
    -n 1:0:+512M   -t 1:ef00 -c 1:"ESP" \
    -n 2:0:+10G    -t 2:8300 -c 2:"Root A" \
    -n 3:0:+10G    -t 3:8300 -c 3:"Root B" \
    -n 4:0:0       -t 4:8300 -c 4:"Data" \
    "$DISK"

partprobe "$DISK"
sleep 1

# --- Format ---
echo ":: Formatting partitions..."
mkfs.fat -F 32 -n HARBOR_ESP "$ESP"
mkfs.ext4 -F -L harbor_root_a "$ROOT_A"
mkfs.ext4 -F -L harbor_root_b "$ROOT_B"
mkfs.ext4 -F -L harbor_data "$DATA"

# --- Write root image to partition A ---
echo ":: Decompressing and writing root image to Root A..."
zstd -d "$IMAGE" --stdout | dd of="$ROOT_A" bs=4M conv=fsync status=progress
sync

# Resize filesystem to fill the partition
echo ":: Resizing filesystem to fill partition..."
e2fsck -f -y "$ROOT_A" || true
resize2fs "$ROOT_A"

# --- Mount and configure boot ---
echo ":: Setting up boot..."
MOUNT_DIR="/tmp/harbor-install-$$"
mkdir -p "${MOUNT_DIR}"

mount "$ROOT_A" "$MOUNT_DIR"
mkdir -p "${MOUNT_DIR}/boot/efi"
mount "$ESP" "${MOUNT_DIR}/boot/efi"

# Get PARTUUIDs
ROOT_A_PARTUUID=$(blkid -s PARTUUID -o value "$ROOT_A")
ROOT_B_PARTUUID=$(blkid -s PARTUUID -o value "$ROOT_B")
DATA_PARTUUID=$(blkid -s PARTUUID -o value "$DATA")

# Install systemd-boot
arch-chroot "$MOUNT_DIR" bootctl install --esp-path=/boot/efi

# Create loader config
cat > "${MOUNT_DIR}/boot/efi/loader/loader.conf" << 'EOF'
default harbor-a.conf
timeout 3
editor  no
EOF

# Create boot entries
cat > "${MOUNT_DIR}/boot/efi/loader/entries/harbor-a.conf" << EOF
title   Harbor Srv (Root A)
linux   /vmlinuz-linux
initrd  /intel-ucode.img
initrd  /initramfs-linux.img
options root=PARTUUID=${ROOT_A_PARTUUID} rw ipv6.disable=1
EOF

cat > "${MOUNT_DIR}/boot/efi/loader/entries/harbor-b.conf" << EOF
title   Harbor Srv (Root B)
linux   /vmlinuz-linux
initrd  /intel-ucode.img
initrd  /initramfs-linux.img
options root=PARTUUID=${ROOT_B_PARTUUID} rw ipv6.disable=1
EOF

# Copy kernel, microcode, and initramfs to ESP so systemd-boot can find them
cp "${MOUNT_DIR}/boot/vmlinuz-linux" "${MOUNT_DIR}/boot/efi/"
cp "${MOUNT_DIR}/boot/intel-ucode.img" "${MOUNT_DIR}/boot/efi/"
cp "${MOUNT_DIR}/boot/initramfs-linux.img" "${MOUNT_DIR}/boot/efi/"

# Create fstab
cat > "${MOUNT_DIR}/etc/fstab" << EOF
# harbor_srv fstab — generated by install.sh
PARTUUID=${ROOT_A_PARTUUID}  /             ext4  rw,relatime  0 1
PARTUUID=$(blkid -s PARTUUID -o value "$ESP")  /boot/efi  vfat  rw,relatime,fmask=0077,dmask=0077  0 2
PARTUUID=${DATA_PARTUUID}    /data         ext4  rw,relatime  0 2
EOF

mkdir -p "${MOUNT_DIR}/data"

# Write partition metadata for deploy script to use
mkdir -p "${MOUNT_DIR}/etc/harbor"
cat > "${MOUNT_DIR}/etc/harbor/partitions.conf" << EOF
# harbor_srv partition PARTUUIDs — written by install.sh
ESP_PARTUUID=$(blkid -s PARTUUID -o value "$ESP")
ROOT_A_PARTUUID=${ROOT_A_PARTUUID}
ROOT_B_PARTUUID=${ROOT_B_PARTUUID}
DATA_PARTUUID=${DATA_PARTUUID}
ROOT_A_DEV=${ROOT_A}
ROOT_B_DEV=${ROOT_B}
EOF

# --- Cleanup ---
echo ":: Unmounting..."
umount "${MOUNT_DIR}/boot/efi"
umount "${MOUNT_DIR}"
rmdir "${MOUNT_DIR}"

echo ""
echo "=== Installation complete ==="
echo "Root A PARTUUID: ${ROOT_A_PARTUUID}"
echo "Root B PARTUUID: ${ROOT_B_PARTUUID}"
echo "Data PARTUUID:   ${DATA_PARTUUID}"
echo ""
echo "Reboot and select the disk in your UEFI boot menu."
echo "Remember to disable Secure Boot!"
