---
name: Build

on:
  push:
    branches: [test]
    paths:
      - 'profile/**'
      - '.github/workflows/**'
  pull_request:
    branches: [main]
    paths:
      - 'profile/**'
      - '.github/workflows/**'

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
    steps:
      - uses: actions/checkout@v5

      - name: Install shellcheck
        run: |
          pacman -Sy --needed --noconfirm archlinux-keyring
          pacman --noconfirm -Syu --needed shellcheck

      - name: Shellcheck
        run: shellcheck profile/profiledef.sh

  build:
    runs-on: ubuntu-latest
    needs: check
    container:
      image: archlinux/archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v5

      - name: Update keyring and install archiso
        run: |
          pacman -Sy --needed --noconfirm archlinux-keyring
          pacman -Syu --needed --noconfirm archiso grub

      - name: Build ISO
        run: mkarchiso -v -m iso -o output/ -w tmp/ profile/

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v5
        with:
          name: harbor_srv-iso
          path: output/
          retention-days: 30
